-- Limpar data
TRUNCATE TABLE exercise;

-- Exercícios para Costas (ID: 1)
INSERT INTO exercise (exerciseID, name, description, videoUrl, imageUrl, category, difficulty, musclegroupid, instructions,
                      tips, warning, benefits)
VALUES 
(UUID(), 'Remada Unilateral com Haltere', 'Exercício que trabalha os músculos das costas e bíceps, realizado com um haltere.',
'remada-unilateral', 'remada-unilateral.jpg', 'Força', 'Médio', 1,
'Com um joelho e uma mão apoiados no banco, puxe o haltere com a outra mão em direção ao corpo.',
'Mantenha a postura reta e concentre-se no movimento de puxar com as costas.',
'Evite balançar o corpo durante o exercício.',
'Trabalha os músculos das costas, melhorando a força e definição.'),
(UUID(), 'Remada Baixa na Máquina', 'Exercício de remada realizado na máquina, focado na parte média das costas.',
'remada-baixa-maquina', 'remada-baixa-maquina.jpg', 'Força', 'Médio', 1,
'Sente-se na máquina e segure as alças. Puxe as alças em direção ao tronco, mantendo os cotovelos próximos ao corpo.',
'Mantenha as costas retas durante o movimento e evite balançar.',
'Não sobrecarregue o peso, pois isso pode prejudicar a execução do movimento.',
'Fortalece os músculos das costas, especialmente os romboides e trapézio.'),
(UUID(), 'Puxada por Trás', 'Exercício de puxada na polia alta, com ênfase nos músculos das costas e ombros.',
'puxada-por-tras', 'puxada-por-tras.jpg', 'Força', 'Médio', 1,
'Use a barra para puxada atrás da cabeça. Puxe a barra até a altura da nuca, concentrando o movimento nas costas.',
'Mantenha a postura ereta, evitando que os ombros se movam excessivamente.',
'Evite sobrecarregar a barra, para evitar sobrecarga nas articulações dos ombros.',
'Fortalece os músculos do dorsal e melhora a amplitude de movimento dos ombros.'),
(UUID(), 'Deadlift com Halteres', 'Variante do levantamento terra, utilizando halteres, que trabalha toda a cadeia posterior das costas.',
'deadlift-com-halteres', 'deadlift-com-halteres.jpg', 'Força', 'Médio', 1,
'Com os pés na largura dos ombros e os halteres nas mãos, execute o levantamento com as costas retas, levando os quadris para trás.',
'Mantenha os halteres perto das pernas e não arqueie as costas.',
'Evite utilizar carga excessiva, garantindo que a técnica seja correta para prevenir lesões.',
'Fortalece as costas, glúteos e posterior de coxas, melhorando a postura e a força.'),
(UUID(), 'Remada com Barra', 'Exercício composto de remada com barra que trabalha a parte média das costas e o trapézio.',
'remada-com-barra', 'remada-com-barra.jpg', 'Força', 'Médio', 1,
'Fique em pé com os pés na largura dos ombros, incline o tronco para frente e puxe a barra em direção ao abdômen.',
'Mantenha os cotovelos próximos ao corpo e o tronco estabilizado.',
'Evite usar o impulso para levantar a barra, controlando o movimento.',
'Fortalece o trapézio, romboides e a parte média das costas, promovendo uma postura mais ereta.'),
(UUID(), 'Pull Over com Haltere', 'Exercício que trabalha o dorsal, realizado com halteres, aumentando a largura das costas.',
'pull-over-com-haltere', 'pull-over-com-haltere.jpg', 'Força', 'Médio', 1,
'Deite-se em um banco e segure um haltere com as duas mãos. Levante o haltere acima da cabeça e, em seguida, retorne à posição inicial.',
'Mantenha os braços ligeiramente flexionados e evite usar o impulso.',
'Não sobrecarregue o peso, pois pode causar desconforto nos ombros.',
'Aumenta a largura das costas e fortalece a região do dorsal, ajudando na melhoria da postura.'),
(UUID(), 'Puxada com Pegada Neutra', 'Exercício que trabalha as costas, realizado na máquina de polia alta com uma pegada neutra.',
'puxada-com-pegada-neutra', 'puxada-com-pegada-neutra.jpg', 'Força', 'Fácil', 1,
'Com uma pegada neutra (palmas voltadas uma para a outra), puxe a barra para baixo, concentrando o movimento nas costas.',
'Mantenha o peito erguido e os ombros para trás durante a execução.',
'Evite usar o impulso ao puxar a barra, focando na ativação dos músculos das costas.',
'Fortalece os músculos das costas, incluindo o latíssimo do dorso (dorsal), ajudando na definição e resistência.'),
(UUID(), 'Barra Fixa com Pegada Aberta', 'Exercício para costas que utiliza a barra fixa, com a pegada mais afastada, enfatizando o trabalho dos músculos dorsais.',
'barra-fixa-com-pegada-aberta', 'barra-fixa-com-pegada-aberta.jpg', 'Força', 'Difícil', 1,
'Pule para a barra fixa e segure-a com as mãos mais afastadas que a largura dos ombros. Puxe-se até que o queixo ultrapasse a barra.',
'Mantenha o corpo reto e evite usar o impulso para realizar o movimento.',
'Não force o movimento, especialmente se não conseguir completar a repetição.',
'Fortalece os músculos das costas, especialmente o latíssimo do dorso (dorsal), ajudando na definição e no aumento da força.'),
(UUID(), 'Remada Sentada na Polia Baixa', 'Exercício de remada realizado na máquina de polia baixa, com a pegada neutra ou em pronada, para trabalhar as costas.',
'remada-sentada-na-polia-baixa', 'remada-sentada-na-polia-baixa.jpg', 'Força', 'Médio', 1,
'Sente-se na máquina de remada baixa e puxe a barra em direção ao abdômen, mantendo os cotovelos fixos ao corpo.',
'Mantenha as costas retas durante o exercício, evitando que o tronco se movimente.',
'Não sobrecarregue o peso, pois isso pode comprometer a forma do movimento.',
'Fortalece as costas médias e superiores, especialmente romboides e trapézio.'),
(UUID(), 'Remada com Pegada Invertida', 'Exercício de remada com a barra, usando pegada invertida, que foca nos músculos das costas e bíceps.',
'remada-com-pegada-invertida', 'remada-com-pegada-invertida.jpg', 'Força', 'Médio', 1,
'Fique em pé com os pés afastados e pegue a barra com as palmas voltadas para cima. Puxe a barra em direção ao tronco, mantendo os cotovelos para trás.',
'Mantenha os ombros para trás e os cotovelos fixos durante o movimento.',
'Não use impulso para levantar a barra, garantindo que o movimento venha da força das costas e bíceps.',
'Aumenta a força nos músculos das costas, além de trabalhar o bíceps de forma eficiente.');

-- Exercícios para Bíceps (ID: 2)
INSERT INTO exercise (exerciseID, name, description, videoUrl, imageUrl, category, difficulty, musclegroupid, instructions,
                      tips, warning, benefits)
VALUES 
(UUID(), 'Rosca Direta com Barra', 'Exercício clássico para trabalhar os bíceps, usando barra para melhor estabilidade e foco no músculo.',
'rosca-direta-com-barra', 'rosca-direta-com-barra.jpg', 'Força', 'Fácil', 2,
'Fique em pé com a barra nas mãos, com os cotovelos próximos ao corpo. Levante a barra até a altura do peito e abaixe controladamente.',
'Mantenha os cotovelos fixos e evite balançar o corpo.',
'Evite sobrecarregar e fazer movimentos bruscos para prevenir lesões.',
'Fortalece e define os bíceps, melhorando a estética dos braços.'),
(UUID(), 'Rosca Scott', 'Exercício isolado para o bíceps, realizado na máquina ou banco específico, com o objetivo de melhorar a definição e força.',
'rosca-scott', 'rosca-scott.jpg', 'Força', 'Médio', 2,
'Sente-se no banco Scott, com os cotovelos apoiados. Levante a barra ou halteres até o nível do peito e retorne controladamente.',
'Evite usar impulso e mantenha os cotovelos fixos.',
'Não sobrecarregue o peso, pois isso pode comprometer a técnica.',
'Melhora a definição e a força do bíceps, isolando a musculatura do braço.'),
(UUID(), 'Rosca Martelo', 'Exercício para os bíceps, utilizando halteres com pegada neutra, que também ativa o antebraço.',
'rosca-martelo', 'rosca-martelo.jpg', 'Força', 'Médio', 2,
'Fique em pé, segure os halteres com as palmas voltadas uma para a outra. Flexione os cotovelos, levantando os pesos até a altura do ombro.',
'Mantenha os cotovelos fixos e evite o uso de impulso.',
'Não sobrecarregue os pesos para evitar lesões nos ombros e cotovelos.',
'Trabalha os bíceps e antebraços, aumentando a força e a definição.'),
(UUID(), 'Rosca Alternada com Halteres', 'Exercício que trabalha de forma isolada cada bíceps, utilizando halteres, sendo ótimo para aumentar a simetria.',
'rosca-alternada-com-halteres', 'rosca-alternada-com-halteres.jpg', 'Força', 'Fácil', 2,
'Com um haltere em cada mão, levante alternadamente os pesos até a altura do ombro, controlando o movimento.',
'Não balance os halteres. Mantenha os cotovelos próximos ao corpo.',
'Evite sobrecarga excessiva para não comprometer a forma do movimento.',
'Melhora a definição e simetria dos bíceps.'),
(UUID(), 'Rosca Inclinada', 'Exercício para os bíceps realizado em banco inclinado, o que aumenta o estiramento e a carga nos músculos.',
'rosca-inclinada', 'rosca-inclinada.jpg', 'Força', 'Médio', 2,
'Sente-se em um banco inclinado e segure os halteres. Execute a rosca flexionando os cotovelos até a altura do ombro.',
'Mantenha os cotovelos fixos e evite balançar os halteres.',
'Não exagere no peso, pois a técnica é crucial para o sucesso do exercício.',
'Aumenta a amplitude de movimento, potencializando o trabalho muscular nos bíceps.'),
(UUID(), 'Rosca 21', 'Exercício para os bíceps em que realiza 7 repetições na parte inferior, 7 na superior e 7 completas, totalizando 21 movimentos.',
'rosca-21', 'rosca-21.jpg', 'Força', 'Médio', 2,
'Execute a rosca, fazendo 7 repetições na parte inferior, 7 na parte superior e 7 completas.',
'Mantenha o controle durante todo o movimento e evite balançar o corpo.',
'Evite sobrecarregar para manter o controle da técnica.',
'Estimula tanto a força quanto a resistência dos bíceps, promovendo ganhos significativos de volume.'),
(UUID(), 'Rosca Concentrada', 'Exercício de isolamento que trabalha intensamente os bíceps, realizado sentado e com halteres.',
'rosca-concentrada', 'rosca-concentrada.jpg', 'Força', 'Médio', 2,
'Sente-se em um banco, segure um haltere com uma mão e apoie o cotovelo na parte interna da coxa. Flexione o cotovelo, levantando o haltere.',
'Evite usar impulso. Mantenha os cotovelos fixos.',
'Não sobrecarregue os halteres, use pesos moderados para garantir a execução correta.',
'Melhora a definição e a força do bíceps, proporcionando um ótimo isolamento do músculo.'),
(UUID(), 'Rosca Bíceps na Máquina', 'Exercício para os bíceps utilizando a máquina de rosca, permitindo uma execução mais isolada e controlada.',
'rosca-biceps-na-maquina', 'rosca-biceps-na-maquina.jpg', 'Força', 'Fácil', 2,
'Sente-se na máquina de rosca e segure as alças. Flexione os cotovelos, levantando o peso até a altura dos ombros.',
'Mantenha os cotovelos próximos ao corpo e evite movimentos bruscos.',
'Não sobrecarregue o peso e use uma carga que permita boa execução.',
'Excelente para quem busca foco nos bíceps com menos risco de lesão.'),
(UUID(), 'Rosca Bíceps com Cabo', 'Exercício utilizando cabo, que proporciona resistência constante durante todo o movimento.',
'rosca-biceps-com-cabo', 'rosca-biceps-com-cabo.jpg', 'Força', 'Médio', 2,
'Segure as alças do cabo com as palmas das mãos voltadas para cima. Flexione os cotovelos para levantar o peso até a altura do peito.',
'Mantenha os cotovelos fixos e evite o uso de impulso.',
'Evite sobrecarregar o cabo, pois pode comprometer o controle do movimento.',
'Trabalha os bíceps com ênfase na contração máxima e resistência contínua.'),
(UUID(), 'Barra Fixa (Pull-up)', 'Exercício de peso corporal para os bíceps e costas, com o objetivo de aumentar a força e resistência na parte superior do corpo.',
'barra-fixa', 'barra-fixa.jpg', 'Força', 'Difícil', 2,
'Pendure-se na barra com as mãos afastadas e puxe o corpo para cima até que o queixo ultrapasse a barra.',
'Evite usar impulso e balance o corpo.',
'Evite dores nas articulações dos ombros, e se necessário, comece com auxílio.',
'Fortalece os bíceps e as costas, melhorando a força da parte superior do corpo.');

-- Exercícios para Tríceps (ID: 3)
INSERT INTO exercise (exerciseID, name, description, videoUrl, imageUrl, category, difficulty, musclegroupid, instructions,
                      tips, warning, benefits)
VALUES 
(UUID(), 'Tríceps na Polia Alta', 'Exercício isolado para os tríceps, realizado com a polia alta para ajudar no desenvolvimento da parte posterior dos braços.',
'triceps-na-polia-alta', 'triceps-na-polia-alta.jpg', 'Força', 'Fácil', 3,
'Fique em pé, segure a corda na polia alta, e empurre-a para baixo até os braços ficarem esticados, retornando lentamente.',
'Mantenha os cotovelos próximos ao corpo e evite movimentos bruscos.',
'Evite sobrecarregar a máquina e mantenha o controle total do movimento.',
'Fortalece e define os tríceps, melhorando a estética dos braços.'),
(UUID(), 'Mergulho entre Bancos', 'Exercício de força que utiliza o peso do corpo para trabalhar os tríceps.',
'mergulho-entre-bancos', 'mergulho-entre-bancos.jpg', 'Força', 'Médio', 3,
'Sente-se entre dois bancos, coloque as mãos nos bancos e os pés no outro. Abaixe o corpo controladamente e empurre para cima.',
'Mantenha os cotovelos próximos ao corpo e evite arquear os ombros.',
'Não sobrecarregue os ombros e evite dor no cotovelo.',
'Fortalece os tríceps, melhorando o contorno dos braços.'),
(UUID(), 'Tríceps Testa', 'Exercício isolado que foca no tríceps, realizado deitado em banco com barra ou halteres.',
'triceps-testa', 'triceps-testa.jpg', 'Força', 'Médio', 3,
'Deitado no banco, segure a barra com as mãos afastadas e leve a barra em direção à testa. Estenda os braços para cima.',
'Evite descer a barra muito abaixo da testa e mantenha o controle total.',
'Não sobrecarregue a barra, pois o exercício exige boa técnica.',
'Isola o tríceps, promovendo força e definição nos braços.'),
(UUID(), 'Mergulho no Banco', 'Exercício simples, porém eficaz para os tríceps, utilizando o peso do corpo.',
'mergulho-no-banco', 'mergulho-no-banco.jpg', 'Força', 'Médio', 3,
'Sente-se no banco, mãos apoiadas ao lado do corpo. Abaixe o corpo até os cotovelos formarem um ângulo de 90 graus e empurre para cima.',
'Mantenha os cotovelos fixos e evite que os ombros subam.',
'Evite sobrecarregar os ombros para não gerar lesões.',
'Fortalece os tríceps e melhora a resistência muscular.'),
(UUID(), 'Tríceps Kickback', 'Exercício isolado que trabalha os tríceps, utilizando halteres para extensão do braço.',
'triceps-kickback', 'triceps-kickback.jpg', 'Força', 'Fácil', 3,
'Com um haltere em cada mão, incline-se ligeiramente para frente e estenda os braços para trás.',
'Mantenha o tronco firme e evite balançar os halteres.',
'Use pesos moderados para garantir o controle do movimento.',
'Isola o tríceps, aumentando a definição muscular e a força da parte posterior dos braços.');

-- Exercícios para Abdômen (ID: 4)
INSERT INTO exercise (exerciseID, name, description, videoUrl, imageUrl, category, difficulty, musclegroupid, instructions,
                      tips, warning, benefits)
VALUES 
(UUID(), 'Prancha', 'Exercício de isometria para trabalhar o core, focando principalmente nos músculos abdominais e lombares.',
'prancha', 'prancha.jpg', 'Core', 'Médio', 4,
'Fique deitado de bruços, apoie os cotovelos e os pés no chão, mantendo o corpo alinhado. Mantenha a posição pelo maior tempo possível.',
'Mantenha o corpo reto e contraído durante o exercício.',
'Evite deixar o quadril muito baixo ou alto, pois isso pode causar lesões na lombar.',
'Fortalece o core, melhora a postura e a estabilidade do corpo.'),
(UUID(), 'Crunch', 'Exercício clássico de abdômen, que foca na parte superior do abdômen.',
'crunch', 'crunch.jpg', 'Core', 'Fácil', 4,
'Deite-se de costas, com os joelhos flexionados. Eleve a parte superior do corpo em direção aos joelhos e volte lentamente.',
'Evite puxar a cabeça com as mãos, apenas contraia o abdômen.',
'Não faça o movimento rápido demais, para evitar lesões no pescoço.',
'Trabalha a parte superior do abdômen, promovendo definição e força.'),
(UUID(), 'Abdominal Reverso', 'Exercício que trabalha principalmente a parte inferior do abdômen.',
'abdominal-reverso', 'abdominal-reverso.jpg', 'Core', 'Médio', 4,
'Deite-se de costas, com as pernas levantadas. Dobre os joelhos e traga-os em direção ao peito, contraindo o abdômen.',
'Evite puxar o pescoço e foque no movimento controlado dos quadris.',
'Não levante o pescoço ou ombros do chão, para evitar tensão na região cervical.',
'Fortalece a parte inferior do abdômen, melhorando a resistência muscular.'),
(UUID(), 'Bicicleta no Solo', 'Exercício dinâmico que trabalha tanto o abdômen quanto os oblíquos.',
'bicicleta-no-solo', 'bicicleta-no-solo.jpg', 'Core', 'Médio', 4,
'Deite-se de costas, com as mãos atrás da cabeça. Faça movimentos alternados de pedalada, trazendo o cotovelo em direção ao joelho oposto.',
'Mantenha os movimentos fluidos e evite forçar o pescoço.',
'Não puxe a cabeça com as mãos para evitar tensão na região cervical.',
'Fortalece os abdominais e oblíquos, além de melhorar a coordenação motora.'),
(UUID(), 'Russian Twist', 'Exercício que trabalha os oblíquos e a parte lateral do abdômen.',
'russian-twist', 'russian-twist.jpg', 'Core', 'Fácil', 4,
'Sente-se no chão com as pernas elevadas e cruzadas, segurando um peso ou sem peso. Gire o tronco para os lados, mantendo o abdômen contraído.',
'Mantenha a coluna ereta durante o movimento.',
'Não gire rapidamente o tronco para evitar lesões nas costas.',
'Aumenta a definição nos oblíquos, tonificando a cintura.'),
(UUID(), 'Leg Raise', 'Exercício para trabalhar a parte inferior do abdômen, com ênfase no controle das pernas.',
'leg-raise', 'leg-raise.jpg', 'Core', 'Médio', 4,
'Deite-se de costas, com as pernas esticadas. Levante as pernas até formar um ângulo de 90 graus e abaixe lentamente.',
'Mantenha a lombar pressionada contra o chão durante o movimento.',
'Não arqueie as costas ao levantar as pernas, pois isso pode causar desconforto na região lombar.',
'Trabalha os músculos abdominais inferiores, ajudando na definição da região abdominal.'),
(UUID(), 'Mountain Climbers', 'Exercício dinâmico de core, que trabalha tanto o abdômen quanto os músculos das pernas e braços.',
'mountain-climbers', 'mountain-climbers.jpg', 'Core', 'Fácil', 4,
'Comece na posição de prancha e alterne entre levar um joelho em direção ao peito e depois o outro, mantendo um ritmo rápido.',
'Mantenha o abdômen contraído e os quadris estáveis.',
'Não deixe os quadris subirem ou descerem excessivamente durante o movimento.',
'Aumenta a resistência e a definição no abdômen, além de ser um bom exercício cardiovascular.'),
(UUID(), 'V-Sit Up', 'Exercício de abdômen avançado que trabalha tanto a parte superior quanto a inferior do abdômen.',
'v-sit-up', 'v-sit-up.jpg', 'Core', 'Difícil', 4,
'Deite-se de costas e levante as pernas esticadas ao mesmo tempo que a parte superior do corpo, tentando tocar os pés com as mãos.',
'Mantenha os movimentos controlados, evitando que o pescoço se sobrecarregue.',
'Evite usar impulso, garantindo que o movimento seja controlado e focado nos músculos abdominais.',
'Aumenta a força e a resistência abdominal, ajudando a melhorar o tônus muscular.'),
(UUID(), 'Abdominal no Banco Inclinado', 'Exercício de abdômen realizado em banco inclinado, proporcionando maior intensidade ao movimento.',
'abdominal-no-banco-inclinado', 'abdominal-no-banco-inclinado.jpg', 'Core', 'Médio', 4,
'Deite-se no banco inclinado, segure as alças e execute o movimento de abdominal, subindo e descendo a parte superior do corpo.',
'Evite puxar a cabeça e mantenha o abdômen contraído durante o movimento.',
'Não arqueie as costas, mantendo sempre o controle total do movimento.',
'Aumenta a intensidade do treinamento abdominal, promovendo mais definição e força.'),
(UUID(), 'Plank com Toque no Ombro', 'Versão avançada da prancha, com o objetivo de melhorar a estabilidade do core e a força dos ombros.',
'plank-com-toque-no-ombro', 'plank-com-toque-no-ombro.jpg', 'Core', 'Difícil', 4,
'Fique na posição de prancha e alterne tocando um ombro com a mão oposta, mantendo o corpo alinhado.',
'Evite balançar o corpo para não perder a estabilidade.',
'Não deixe os quadris descerem ou subirem durante o movimento.',
'Fortalece o core, os ombros e melhora a estabilidade corporal.');

-- Exercícios para Glúteos (ID: 5)
INSERT INTO exercise (exerciseID, name, description, videoUrl, imageUrl, category, difficulty, musclegroupid, instructions,
                      tips, warning, benefits)
VALUES 
(UUID(), 'Hip Thrust', 'Exercício excelente para isolar e ativar os glúteos, melhorando sua força e forma.',
'hip-thrust', 'hip-thrust.jpg', 'Força', 'Difícil', 5,
'Posicione as costas apoiadas em um banco e os pés no chão. Levante o quadril para cima, apertando os glúteos no topo do movimento e abaixe novamente.',
'Mantenha os ombros relaxados e evite sobrecarregar a lombar.',
'Evite o uso de carga excessiva sem a técnica adequada para prevenir lesões.',
'Foca na ativação dos glúteos, promovendo aumento de força e hipertrofia muscular.'),
(UUID(), 'Agachamento', 'Exercício clássico que trabalha os glúteos, quadríceps e parte posterior das coxas. O agachamento é ótimo para força e hipertrofia.',
'agachamento', 'agachamento.jpg', 'Força', 'Difícil', 5,
'Fique em pé com os pés na largura dos ombros. Agache-se até que as coxas fiquem paralelas ao chão e, em seguida, suba novamente.',
'Mantenha os joelhos alinhados com os pés e as costas retas durante o movimento.',
'Evite que os joelhos ultrapassem os pés para evitar sobrecarga nas articulações.',
'Aumenta a força e a massa muscular dos glúteos, quadríceps e isquiotibiais, além de melhorar a mobilidade da pelve.'),
(UUID(), 'Avanço', 'Exercício unilateral que trabalha os glúteos e quadríceps, excelente para equilibrar a força entre as pernas.',
'avanco', 'avanco.jpg', 'Força', 'Médio', 5,
'Dê um passo à frente com uma perna e abaixe o corpo até que o joelho de trás quase toque o chão. Depois, retorne à posição inicial e repita com a outra perna.',
'Mantenha o tronco ereto durante todo o movimento.',
'Evite que o joelho da perna da frente ultrapasse os dedos do pé.',
'Melhora o equilíbrio e fortalece os glúteos e quadríceps, além de ajudar na tonificação muscular.'),
(UUID(), 'Cadeira Abdutora', 'Máquina que trabalha a parte externa dos glúteos e coxas, ajudando a desenvolver a musculatura lateral.',
'cadeira-abdutora', 'cadeira-abdutora.jpg', 'Força', 'Fácil', 5,
'Sente-se na cadeira abdutora, ajuste a máquina e empurre as almofadas para fora, mantendo as pernas afastadas.',
'Mantenha a postura ereta e concentre-se em usar os músculos do glúteo para mover as pernas.',
'Evite usar carga excessiva, pois isso pode comprometer o movimento.',
'Isola os glúteos, ajudando a melhorar a forma e a tonificação muscular da região lateral das coxas.'),
(UUID(), 'Elevação Pélvica', 'Exercício similar ao Hip Thrust, mas realizado com o corpo em posição mais baixa, com foco nos glúteos e isquiotibiais.',
'elevacao-pelvica', 'elevacao-pelvica.jpg', 'Força', 'Médio', 5,
'Deite-se no chão, com os pés apoiados no solo e as pernas dobradas. Levante o quadril para cima e aperte os glúteos no topo do movimento.',
'Não deixe que os ombros subam ou que a lombar seja sobrecarregada.',
'Mantenha o movimento controlado, sem usar impulso.',
'Fortalece os glúteos e isquiotibiais, além de melhorar a estabilidade do core.'),
(UUID(), 'Stiff', 'Exercício que foca nos isquiotibiais e glúteos, com ênfase na parte posterior das coxas.',
'stiff', 'stiff.jpg', 'Força', 'Médio', 5,
'Segure uma barra com as mãos na frente do corpo, com os pés na largura dos ombros. Flexione os quadris e desça a barra até a altura das canelas antes de voltar à posição inicial.',
'Mantenha a coluna reta durante todo o movimento e evite arredondar as costas.',
'Não use carga excessiva, pois isso pode gerar lesões na lombar.',
'Excelente para isolar os glúteos e isquiotibiais, além de melhorar a flexibilidade dos posteriores de coxa.'),
(UUID(), 'Ponte com os pés elevados', 'Variante da elevação pélvica com os pés elevados, intensificando a ativação dos glúteos.',
'ponte-com-os-pes-elevados', 'ponte-com-os-pes-elevados.jpg', 'Força', 'Médio', 5,
'Deite-se com os pés apoiados em um banco ou plataforma elevada. Levante o quadril para cima, apertando os glúteos no topo do movimento.',
'Mantenha a coluna alinhada e evite usar impulso para subir.',
'Não deixe que os joelhos se abram excessivamente durante o movimento.',
'Aumenta a força dos glúteos e isquiotibiais, além de melhorar a estabilidade do core e a flexibilidade.'),
(UUID(), 'Glúteo 4 Apoios', 'Exercício unilateral realizado no solo, focando nos glúteos e quadríceps.',
'gluteo-4-apoios', 'gluteo-4-apoios.jpg', 'Força', 'Fácil', 5,
'Em posição de 4 apoios (mãos e joelhos no chão), levante uma perna para trás e para cima, apertando os glúteos no topo do movimento.',
'Mantenha o tronco firme e evite arquear a lombar.',
'Controle o movimento e não use impulso para evitar lesões.',
'Ativa bem os glúteos e pode ser realizado sem necessidade de equipamentos, sendo ótimo para iniciantes.'),
(UUID(), 'Kettlebell Swing', 'Exercício com kettlebell que trabalha os glúteos e isquiotibiais, além de melhorar a coordenação e potência.',
'kettlebell-swing', 'kettlebell-swing.jpg', 'Força', 'Médio', 5,
'Segure o kettlebell com as duas mãos, dobre os quadris e balance o kettlebell para frente e para trás, levantando-o até a altura dos ombros.',
'Mantenha a postura ereta e evite usar os braços para impulsionar o kettlebell.',
'Evite usar carga muito pesada se você não dominar a técnica.',
'Ótimo para ativar os glúteos e isquiotibiais, além de melhorar a resistência cardiovascular e a coordenação motora.');

-- Exercícios para Quadríceps (ID: 6)
INSERT INTO exercise (exerciseID, name, description, videoUrl, imageUrl, category, difficulty, musclegroupid, instructions,
                      tips, warning, benefits)
VALUES 
(UUID(), 'Agachamento Livre', 'Exercício fundamental que trabalha os quadríceps, glúteos e a parte posterior das pernas. Pode ser feito com barra ou apenas com o peso do corpo.',
'agachamento-livre', 'agachamento-livre.jpg', 'Força', 'Difícil', 6,
'Fique em pé com os pés na largura dos ombros, segure a barra atrás da cabeça e agache-se até que as coxas fiquem paralelas ao chão.',
'Mantenha as costas retas e o joelho alinhado com os pés durante o movimento.',
'Evite que os joelhos ultrapassem a linha dos pés para não sobrecarregar as articulações.',
'Fortalece os quadríceps, glúteos e a parte posterior das coxas, além de melhorar a mobilidade e estabilidade das articulações.'),
(UUID(), 'Leg Press', 'Máquina que permite um movimento de empurrar com as pernas, focando principalmente nos quadríceps, mas também ativando glúteos e panturrilhas.',
'leg-press', 'leg-press.jpg', 'Força', 'Médio', 6,
'Sente-se na máquina com os pés posicionados na plataforma. Empurre a plataforma para cima até que as pernas fiquem quase estendidas, depois volte lentamente.',
'Mantenha os pés firmes e evite esticar completamente os joelhos para proteger as articulações.',
'Não use carga excessiva para evitar sobrecarga na região lombar.',
'Aumenta a força dos quadríceps, glúteos e panturrilhas, com foco na parte frontal das coxas.'),
(UUID(), 'Agachamento Hack', 'Máquina específica para o agachamento que foca nos quadríceps, permitindo maior controle e segurança durante o movimento.',
'agachamento-hack', 'agachamento-hack.jpg', 'Força', 'Médio', 6,
'Posicione-se na máquina com as costas contra o encosto e os pés posicionados na plataforma. Agache-se até as coxas ficarem paralelas ao chão e depois volte à posição inicial.',
'Mantenha a postura reta durante todo o movimento e evite arquear a lombar.',
'Não use uma carga muito alta, pois o movimento envolve bastante flexão dos joelhos.',
'Foca no desenvolvimento dos quadríceps, com ênfase na parte anterior das coxas.'),
(UUID(), 'Cadeira Extensora', 'Máquina que isola os quadríceps, proporcionando um excelente trabalho para a parte frontal das coxas.',
'cadeira-extensora', 'cadeira-extensora.jpg', 'Força', 'Fácil', 6,
'Sente-se na cadeira extensora, ajuste o apoio para que fique acima dos tornozelos e estenda as pernas até que estejam completamente retas.',
'Evite usar peso excessivo para não comprometer a execução do movimento.',
'Não permita que os joelhos se movam lateralmente durante o exercício.',
'Isola os quadríceps, proporcionando um ótimo desenvolvimento e definição da parte frontal das coxas.'),
(UUID(), 'Agachamento Frontal', 'Variante do agachamento, em que a barra é posicionada na frente do corpo, ativando mais os quadríceps e menos os glúteos e posteriores.',
'agachamento-frontal', 'agachamento-frontal.jpg', 'Força', 'Difícil', 6,
'Posicione a barra na parte da frente dos ombros e agache-se, mantendo o tronco ereto e as coxas paralelas ao chão.',
'Mantenha o peito para cima e evite que os joelhos ultrapassem os pés.',
'Evite sobrecarregar o movimento com muita carga. O foco é na técnica e controle.',
'Trabalha de maneira eficiente os quadríceps, além de promover mais mobilidade e força para as articulações.'),
(UUID(), 'Afundo', 'Exercício unilateral que trabalha os quadríceps, glúteos e os músculos estabilizadores das pernas.',
'afundo', 'afundo.jpg', 'Força', 'Médio', 6,
'Com um haltere em cada mão, dê um passo à frente e agache-se até que o joelho da perna de trás quase toque o chão.',
'Mantenha o joelho da frente alinhado com o pé e evite que ele ultrapasse a linha dos dedos.',
'Não use carga excessiva, pois o foco é o movimento controlado e profundo.',
'Excelente para o desenvolvimento dos quadríceps e glúteos, além de melhorar o equilíbrio e estabilidade das pernas.'),
(UUID(), 'Cadeira Abdutora', 'Máquina que trabalha a parte externa das coxas, ativando os músculos adutores, mas também tem influência sobre os quadríceps.',
'cadeira-abdutora', 'cadeira-abdutora.jpg', 'Força', 'Fácil', 6,
'Sente-se na cadeira, posicione as pernas para dentro e empurre as almofadas para fora até que as pernas fiquem totalmente estendidas.',
'Mantenha a posição dos pés e evite movimento excessivo para evitar tensão nas articulações.',
'Não use carga excessiva, pois o movimento é de amplitude pequena.',
'Fortalece os quadríceps e glúteos, além de trabalhar a parte externa das coxas.'),
(UUID(), 'Agachamento Sumô', 'Variante do agachamento, com os pés mais afastados, trabalhando os quadríceps e adutores em maior grau.',
'agachamento-sumo', 'agachamento-sumo.jpg', 'Força', 'Médio', 6,
'Com os pés afastados e os dedos apontando para fora, agache-se mantendo a postura reta e os joelhos alinhados com os pés.',
'Mantenha a barra perto do corpo durante todo o movimento e evite que os joelhos saiam do alinhamento.',
'Não agache abaixo de 90 graus sem a técnica adequada, pois pode gerar lesões nas articulações.',
'Trabalha os quadríceps, glúteos e adutores, ajudando a melhorar a flexibilidade e força das pernas.'),
(UUID(), 'Pistol Squat', 'Agachamento unilateral, com foco intenso no quadríceps, glúteos e core, sendo um dos exercícios mais desafiadores.',
'pistol-squat', 'pistol-squat.jpg', 'Força', 'Difícil', 6,
'Fique em pé sobre uma perna e agache-se enquanto a outra perna permanece estendida à frente.',
'Mantenha o equilíbrio durante todo o movimento, e evite que o joelho ultrapasse os pés.',
'Não tente o exercício sem antes desenvolver a força e mobilidade necessárias.',
'Foca no desenvolvimento do quadríceps, glúteos e core, além de melhorar o equilíbrio e a coordenação motora.');

-- Exercícios para Posteriores de Coxas (ID: 7)
INSERT INTO exercise (exerciseID, name, description, videoUrl, imageUrl, category, difficulty, musclegroupid, instructions,
                      tips, warning, benefits)
VALUES 
(UUID(), 'Flexão de Pernas na Máquina', 'Exercício de isolamento para trabalhar os músculos posteriores de coxa (hamstrings).',
'flexao-de-pernas-na-maquina', 'flexao-de-pernas-na-maquina.jpg', 'Força', 'Fácil', 7,
'Deite-se de barriga para baixo na máquina de flexão de pernas. Flexione as pernas em direção aos glúteos, contraindo os músculos posteriores de coxa.',
'Mantenha os quadris pressionados contra o banco e evite levantar a pelve.',
'Evite sobrecarregar a máquina para não forçar os joelhos.',
'Fortalece os músculos posteriores de coxa, melhorando a força e o equilíbrio muscular.'),
(UUID(), 'Stiff', 'Exercício com barra ou halteres, ótimo para trabalhar os músculos posteriores de coxa e glúteos.',
'stiff', 'stiff.jpg', 'Força', 'Médio', 7,
'Com a barra ou halteres, mantenha os pés na largura dos ombros. Incline o tronco para frente, mantendo as pernas ligeiramente flexionadas, e retorne à posição inicial.',
'Evite arredondar as costas durante o movimento.',
'Não sobrecarregue o peso, pois o movimento exige controle e técnica.',
'Trabalha os posteriores de coxa e glúteos, promovendo força e resistência.'),
(UUID(), 'Mesa Flexora', 'Exercício isolado para os posteriores de coxa realizado na mesa flexora.',
'mesa-flexora', 'mesa-flexora.jpg', 'Força', 'Fácil', 7,
'Ajuste a máquina e posicione as pernas, realizando o movimento de flexão para contrair os músculos posteriores.',
'Mantenha o movimento controlado e evite movimentos rápidos.',
'Não use peso excessivo que possa comprometer a forma e a execução do movimento.',
'Fortalece os músculos posteriores de coxa, auxiliando na flexibilidade e no equilíbrio muscular.');

-- Exercícios para Panturrilhas (ID: 8)
INSERT INTO exercise (exerciseID, name, description, videoUrl, imageUrl, category, difficulty, musclegroupid, instructions,
                      tips, warning, benefits)
VALUES 
(UUID(), 'Elevação de Panturrilha em Pé', 'Exercício clássico para trabalhar as panturrilhas, realizado com o peso do corpo ou com carga adicional.',
'elevacao-de-panturrilha-em-pe', 'elevacao-de-panturrilha-em-pe.jpg', 'Força', 'Fácil', 8,
'Fique em pé, com os pés alinhados aos ombros. Levante os calcanhares, mantendo os joelhos esticados, e retorne.',
'Não faça o movimento rápido, o foco deve estar na contração das panturrilhas.',
'Mantenha o controle e evite levantar os calcanhares muito rápido.',
'Fortalece as panturrilhas, melhorando a resistência e a estética das pernas.'),
(UUID(), 'Elevação de Panturrilha Sentado', 'Exercício realizado sentado, ideal para trabalhar a parte inferior das panturrilhas.',
'elevacao-de-panturrilha-sentado', 'elevacao-de-panturrilha-sentado.jpg', 'Força', 'Médio', 8,
'Sente-se no banco e coloque um peso sobre as coxas. Levante os calcanhares, contraindo as panturrilhas.',
'Mantenha os pés totalmente apoiados na plataforma.',
'Evite sobrecarga para evitar lesões nos joelhos.',
'Foca nas panturrilhas, proporcionando força e resistência na parte inferior das pernas.'),
(UUID(), 'Panturrilha na Leg Press', 'Exercício de panturrilha realizado na máquina de leg press, com resistência constante.',
'panturrilha-na-leg-press', 'panturrilha-na-leg-press.jpg', 'Força', 'Médio', 8,
'Ajuste a plataforma de leg press, empurre com as pontas dos pés, elevando os calcanhares.',
'Evite dobrar os joelhos durante o movimento.',
'Não sobrecarregue a máquina, pois isso pode comprometer a execução do movimento.',
'Fortalece as panturrilhas e ajuda a melhorar a resistência muscular nas pernas.');

-- Exercícios para Peito (ID: 9)
INSERT INTO exercise (exerciseID, name, description, videoUrl, imageUrl, category, difficulty, musclegroupid, instructions,
                      tips, warning, benefits)
VALUES 
(UUID(), 'Supino Reto com Barra', 'Exercício básico para trabalhar o peitoral, realizado no banco reto com barra, também ativando os tríceps e ombros.',
'supino-reto-com-barra', 'supino-reto-com-barra.jpg', 'Força', 'Médio', 9,
'Deite-se no banco reto e segure a barra com as mãos um pouco mais afastadas que a largura dos ombros. Abaixe a barra até o peito e empurre de volta.',
'Evite arquear a lombar e balance o peso. Mantenha os pés firmes no chão.',
'Não sobrecarregue a barra sem técnica adequada para evitar lesões nos ombros e coluna.',
'Fortalece o peitoral maior, tríceps e ombros, melhorando a força e estabilidade da parte superior do corpo.'),
(UUID(), 'Supino Inclinado com Halteres', 'Variante do supino, realizada em um banco inclinado com halteres, que foca mais na parte superior do peitoral.',
'supino-inclinado-com-halteres', 'supino-inclinado-com-halteres.jpg', 'Força', 'Médio', 9,
'Deite-se no banco inclinado e segure os halteres na altura do peito. Empurre-os para cima até estender completamente os braços.',
'Mantenha o controle dos halteres durante todo o movimento, evitando o impulso.',
'Evite a sobrecarga, pois isso pode causar lesões nos ombros e articulações.',
'Foca no desenvolvimento da parte superior do peito, além de envolver ombros e tríceps.'),
(UUID(), 'Crossover na Polia', 'Exercício para peitoral que utiliza a máquina de polia, visando o peitoral maior e menor.',
'crossover-na-polia', 'crossover-na-polia.jpg', 'Força', 'Médio', 9,
'Fique em pé com uma polia em cada mão, posicione os pés na largura dos ombros e puxe as polias cruzando-as na frente do corpo.',
'Mantenha uma leve flexão nos cotovelos durante todo o movimento para proteger as articulações.',
'Não use carga excessiva, pois o foco é no controle do movimento e ativação do peitoral.',
'Melhora a definição e força do peitoral, especialmente na região interna.'),
(UUID(), 'Peck Deck', 'Máquina que isola o peitoral maior, excelente para quem busca aumentar a definição do músculo.',
'peck-deck', 'peck-deck.jpg', 'Força', 'Médio', 9,
'Sente-se na máquina, ajuste o banco para que as alças fiquem ao nível do peito e empurre-as para frente.',
'Mantenha a postura ereta, sem curvar a coluna, e concentre-se no movimento do peitoral.',
'Evite sobrecarregar o peso, pois o movimento pode perder o foco no peitoral.',
'Fortalece e define o peitoral maior, auxiliando no aumento da massa muscular.'),
(UUID(), 'Flexão de Braços', 'Exercício clássico de calistenia que trabalha o peitoral, tríceps e ombros, podendo ser realizado em qualquer lugar.',
'flexao-de-bracos', 'flexao-de-bracos.jpg', 'Força', 'Fácil', 9,
'Deite-se no chão, apoie as mãos na largura dos ombros e empurre o corpo para cima, mantendo o corpo reto.',
'Mantenha os cotovelos a 45 graus durante o movimento para proteger os ombros.',
'Não faça o movimento rápido demais e evite curvar a coluna.',
'Fortalece o peitoral, tríceps e ombros, além de ser um ótimo exercício de aquecimento e resistência muscular.'),
(UUID(), 'Supino Declinado com Barra', 'Variante do supino realizado em um banco declinado, que foca a parte inferior do peitoral.',
'supino-declinado-com-barra', 'supino-declinado-com-barra.jpg', 'Força', 'Médio', 9,
'Deite-se no banco declinado e segure a barra na largura dos ombros. Abaixe a barra até a parte inferior do peito e empurre-a de volta.',
'Mantenha os pés bem fixos no banco e os ombros estáveis.',
'Evite realizar o exercício com sobrecarga, pois pode afetar os ombros.',
'Fortalece a parte inferior do peitoral e trabalha também os tríceps e ombros.'),
(UUID(), 'Chest Press na Máquina', 'Máquina de press para peito que permite isolar o movimento e trabalhar o peitoral de forma eficaz.',
'chest-press-na-maquina', 'chest-press-na-maquina.jpg', 'Força', 'Médio', 9,
'Sente-se na máquina, posicione as alças na altura do peito e empurre-as para frente até estender os braços.',
'Evite arquear a lombar durante o movimento, mantendo o corpo estabilizado.',
'Não utilize pesos excessivos, pois o foco é na execução controlada e não na carga.',
'Aumenta a força do peitoral, além de trabalhar os tríceps e ombros de maneira eficaz.'),
(UUID(), 'Crucifixo com Halteres', 'Exercício com halteres que trabalha a região interna do peitoral, realizado deitado no banco.',
'crucifixo-com-halteres', 'crucifixo-com-halteres.jpg', 'Força', 'Médio', 9,
'Deite-se em um banco reto segurando os halteres. Abra os braços para os lados e, em seguida, retorne ao centro.',
'Mantenha uma leve flexão nos cotovelos durante o movimento para evitar sobrecarga nas articulações.',
'Não use peso excessivo, pois o movimento precisa ser controlado e isolado no peitoral.',
'Fortalece a parte interna do peitoral e melhora a definição muscular da região.'),
(UUID(), 'Flexão de Braços com Pés Elevados', 'Variante da flexão, onde os pés são elevados para aumentar a dificuldade e intensificar o trabalho no peitoral superior.',
'flexao-de-bracos-com-pes-elevados', 'flexao-de-bracos-com-pes-elevados.jpg', 'Força', 'Médio', 9,
'Posicione os pés em uma superfície elevada, mantenha as mãos no chão e realize o movimento de flexão como o convencional.',
'Mantenha os cotovelos a 45 graus e o corpo alinhado durante todo o movimento.',
'Não deixe que o quadril desça ou suba, mantendo a postura estável.',
'Intensifica o trabalho do peitoral superior e ajuda na resistência dos tríceps e ombros.'),
(UUID(), 'Dips para Peito', 'Exercício de calistenia que foca no peitoral inferior e tríceps, realizado em barras paralelas.',
'dips-para-peito', 'dips-para-peito.jpg', 'Força', 'Difícil', 9,
'Segure nas barras paralelas e abaixe o corpo até que os cotovelos formem um ângulo de 90 graus. Empurre de volta para a posição inicial.',
'Incline o tronco levemente para frente para focar no peitoral.',
'Não faça o movimento muito rápido e controle o movimento de descida.',
'Fortalece o peitoral inferior, além de trabalhar o tríceps e ombros.');

-- Exercícios para Ombros (ID: 10)
INSERT INTO exercise (exerciseID, name, description, videoUrl, imageUrl, category, difficulty, musclegroupid, instructions,
                      tips, warning, benefits)
VALUES 
(UUID(), 'Desenvolvimento com Barra', 'Exercício composto que trabalha o deltóide, focando principalmente na porção anterior e medial, além de ativar tríceps e trapézio.',
'desenvolvimento-com-barra', 'desenvolvimento-com-barra.jpg', 'Força', 'Médio', 10,
'Fique em pé com os pés na largura dos ombros, segure a barra com as mãos ligeiramente mais afastadas que a largura dos ombros. Empurre a barra para cima até que os braços fiquem estendidos.',
'Mantenha o core ativado e os pés firmes no chão para estabilizar o movimento.',
'Evite a sobrecarga, especialmente se você não tiver controle total sobre o movimento.',
'Desenvolve força e massa muscular no deltóide e nos tríceps, além de melhorar a estabilidade do ombro.'),
(UUID(), 'Desenvolvimento com Halteres', 'Variante do desenvolvimento com barra, realizada com halteres, que permite maior amplitude de movimento e menos sobrecarga nas articulações.',
'desenvolvimento-com-halteres', 'desenvolvimento-com-halteres.jpg', 'Força', 'Médio', 10,
'Sente-se em um banco reto, segure um haltere em cada mão na altura dos ombros. Empurre os halteres para cima até os braços ficarem estendidos.',
'Controle o movimento e evite arquear as costas durante o exercício.',
'Evite movimentos bruscos, pois podem gerar lesões nas articulações dos ombros.',
'Fortalece o deltóide e os tríceps, ajudando na definição e força dos ombros.'),
(UUID(), 'Elevação Lateral com Halteres', 'Exercício isolado que foca no deltóide medial, promovendo a largura dos ombros.',
'elevacao-lateral-com-halteres', 'elevacao-lateral-com-halteres.jpg', 'Força', 'Fácil', 10,
'Fique em pé, segure os halteres ao lado do corpo e levante-os lateralmente até a altura dos ombros.',
'Não use peso excessivo e evite balançar o corpo para realizar o movimento.',
'Não levante os halteres acima da linha dos ombros para evitar sobrecarga.',
'Aumenta a largura dos ombros e define a região do deltóide medial.'),
(UUID(), 'Elevação Frontal com Halteres', 'Exercício que foca na parte anterior do deltóide, melhorando a definição e força desta região.',
'elevacao-frontal-com-halteres', 'elevacao-frontal-com-halteres.jpg', 'Força', 'Fácil', 10,
'Segure os halteres na frente das coxas e levante-os até a altura dos ombros, mantendo os cotovelos ligeiramente flexionados.',
'Evite usar peso excessivo, pois o foco é no controle do movimento.',
'Não arqueie as costas durante o movimento, pois isso pode sobrecarregar a coluna.',
'Desenvolve a parte anterior do deltóide e melhora a definição dos ombros.'),
(UUID(), 'Arnold Press', 'Variante do desenvolvimento com halteres, que envolve uma rotação do braço ao empurrar os halteres, ativando mais fibras musculares do deltóide.',
'arnold-press', 'arnold-press.jpg', 'Força', 'Médio', 10,
'Sente-se em um banco com encosto, segure os halteres na frente do corpo, com as palmas voltadas para o rosto. Empurre os halteres para cima, fazendo uma rotação dos braços.',
'Mantenha a postura reta e o core ativado durante todo o movimento.',
'Evite levantar os halteres acima da linha da cabeça para evitar sobrecarga nos ombros.',
'Foca no desenvolvimento completo do deltóide, ativando as três porções do músculo (anterior, medial e posterior).'),
(UUID(), 'Elevação Posterior com Halteres', 'Exercício isolado que trabalha a porção posterior do deltóide, essencial para um desenvolvimento equilibrado dos ombros.',
'elevacao-posterior-com-halteres', 'elevacao-posterior-com-halteres.jpg', 'Força', 'Médio', 10,
'Incline o tronco para frente, mantendo as costas retas. Segure os halteres com as palmas das mãos voltadas uma para a outra e levante os braços para os lados.',
'Evite usar peso excessivo, pois o exercício foca em uma área menor do músculo.',
'Não deixe os cotovelos se movimentarem demais, o foco é no deltóide posterior.',
'Fortalece a parte posterior dos ombros e melhora a postura e equilíbrio muscular.'),
(UUID(), 'Encolhimento de Ombros com Barra', 'Exercício para o trapézio, que trabalha a parte superior das costas e os músculos dos ombros.',
'encolhimento-de-ombros-com-barra', 'encolhimento-de-ombros-com-barra.jpg', 'Força', 'Fácil', 10,
'Fique em pé, segure a barra com as mãos na largura dos ombros e, com os braços estendidos, encolha os ombros para cima, como se estivesse tentando tocar as orelhas com os ombros.',
'Evite balançar a barra ou utilizar impulso. O movimento deve ser controlado.',
'Não sobrecarregue a barra, o movimento precisa ser feito de forma controlada.',
'Foca no fortalecimento do trapézio e melhora a postura dos ombros.'),
(UUID(), 'Face Pull com Polia Alta', 'Exercício que trabalha a parte posterior dos ombros e a região do trapézio, ajudando a equilibrar os músculos das costas e ombros.',
'face-pull-com-polia-alta', 'face-pull-com-polia-alta.jpg', 'Força', 'Médio', 10,
'Use uma polia alta, segure as cordas com as mãos e puxe em direção ao rosto, mantendo os cotovelos elevados e os ombros para trás.',
'Mantenha o tronco reto durante o movimento, evitando curvar a coluna.',
'Evite puxar com força excessiva, o foco é no controle do movimento e ativação do trapézio e deltóide posterior.',
'Fortalece os músculos posteriores dos ombros e o trapézio, melhorando a postura e estabilidade do ombro.'),
(UUID(), 'Desenvolvimento Militar na Máquina', 'Variante do desenvolvimento de ombro, realizada na máquina, que oferece maior estabilidade durante o movimento.',
'desenvolvimento-militar-na-maquina', 'desenvolvimento-militar-na-maquina.jpg', 'Força', 'Médio', 10,
'Sente-se na máquina e ajuste o assento para que as alças fiquem na altura do ombro. Empurre as alças para cima até os braços ficarem totalmente estendidos.',
'Mantenha os pés firmes no chão e evite arquear a lombar.',
'Não use carga excessiva, pois isso pode prejudicar a execução do movimento.',
'Ajuda a desenvolver o deltóide e os tríceps, com ênfase no aumento da força dos ombros.'),
(UUID(), 'Puxada para Trapézio com Barra', 'Exercício para o trapézio, que visa fortalecer a parte superior das costas e melhorar a estabilidade dos ombros.',
'puxada-para-trapezio-com-barra', 'puxada-para-trapezio-com-barra.jpg', 'Força', 'Médio', 10,
'Com uma barra, fique em pé e puxe a barra na direção do peito, mantendo os cotovelos para trás.',
'Evite curvar as costas ou usar impulso para completar o movimento.',
'Não utilize carga muito elevada, pois o foco é o controle do movimento.',
'Desenvolve a força do trapézio e estabiliza os ombros, ajudando a melhorar a postura e a força das costas.');